### ISSUE TITLE
AssertionError: Trying to copy from a source that does not exist

### ISSUE THREAD

**Issue by kyle-mccarthy** [ommsolutions/generator-next#1] opened 2017-02-13 23:24 UTC
I ran into an issue while trying to run the generator right after installing it.  I follow the directions and the error occurs when trying to write the files.  I have included it below.

For whatever reason my `/usr/local/lib/node_modules/generator-next/generators/app/templates/` directory was missing the `.gitignore`.  I went to this repo copy and pasted the `.gitignore` file from the templates my local `/usr/local/lib/node_modules/generator-next/generators/app/templates/` directory, ran the command again and it worked without any issues.

```
Configuring ...
Writing files ...

events.js:160
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /usr/local/lib/node_modules/generator-next/generators/app/templates/.gitignore
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-next/node_modules/mem-fs-editor/lib/actions/copy.js:47:3)
    at EditionInterface.module.exports [as copyTpl] (/usr/local/lib/node_modules/generator-next/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
    at NExTGenerator.writing (/usr/local/lib/node_modules/generator-next/generators/app/index.js:76:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-next/node_modules/yeoman-generator/lib/index.js:408:23)
    at /usr/local/lib/node_modules/generator-next/node_modules/run-async/index.js:25:25
    at /usr/local/lib/node_modules/generator-next/node_modules/run-async/index.js:24:19
    at /usr/local/lib/node_modules/generator-next/node_modules/yeoman-generator/lib/index.js:409:9
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by enenkel** [comment] 2017-02-14 07:43
Thanks for spotting! The issue is fixed in the latest release.

In case you are interested:
This was actually a known issue of npm. Npm apparently renames ".gitignore" to ".npmignore" on publishing by default ... You never stop learning ;-)
https://github.com/npm/npm/issues/3763

**Closed as completed by enenkel** 2017-02-14 07:43 UTC
Labels: bug, fixed

**Comment by JD1933** [comment] 2020-08-12 11:25
Hi, 
Just letting you know that I just had the same error and had to rename the file to solve it.

**Comment by acoons** [comment] 2020-08-17 07:51
Also encountered this same problem this morning and resolved it in the same manner as described above.
